import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import ContactMe from '../components/ContactMe'
import Banner from '../components/Banner'
import Services from '../components/Servicios'
import Clients from '../components/Clients'
import Team from '../components/Team'
import Proyects from '../components/Proyects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>IvanYaz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Banner/>
        <Services/>
        <Team />
        <Clients />
        <Proyects />
      </main>

      <footer>
        <ContactMe />
        <Footer />
      </footer>
    </div>
  )
}
